---
is:
  keycloak:
    admin:
      user: admin
      password: admin

address:
  ip: 10.3.141.130

server:
  port: 8082

# Keycloak settings
keycloak:
  realm: MyRealm
  auth-server-url: http://10.3.141.130:8180/auth
  ssl-required: none
  resource: backend
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  