---
is:
  keycloak:
    admin:
      user: admin
      password: admin

server:
  port: 8082

# Keycloak settings
keycloak:
  realm: MyRealm
  #STUDIUM
  auth-server-url: http://10.20.72.9:8180/auth
  #CASA
  #auth-server-url: http://192.168.1.100:8180/auth
  ssl-required: none
  resource: backend
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  