---
is:
  keycloak:
    admin:
      user: admin
      password: admin


# Keycloak settings
keycloak:
  realm: MyRealm
  auth-server-url: http://10.3.141.130:8180/auth #http://192.168.1.100:8180/auth
  ssl-required: none
  resource: backend
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  